cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
cask 'xquartz'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'roundup'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
# cask 'tunnelbear'
cask 'vlc'
cask 'iterm2'
brew 'gpg'
cask 'flux'

# brew 'apple-gcc42'
brew 'hub'
brew 'nvm'
brew 'tmate'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'postgresql'
