#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
# todo: make a vim / tmux installer
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# install oh my zsh
# make zsh default
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s $(which zsh)

# rvm, i choose you
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable --ruby

# janus(vim distro) install
curl -L https://bit.ly/janus-bootstrap | bash
ln -s ~/.dotfiles/vim/janus ~/.janus

# tmux
ln -s ~/.dotfiles/tmux.conf ~/.tmux.conf
