#!/usr/bin/env bash

# exit immediately if anything returns non-zero exit code
set -e

if hash apt-get 2>/dev/null; then
  sudo apt-get update
fi

# Run all dotfiles installers.
cd "$(dirname $0)"/..
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
